#
# Vivado (TM) v2016.3 (64-bit)
#
# MUSIC_repo_DA_II.tcl: Tcl script for re-creating project 'music_repo_da_ii'
#
# Generated by Vivado on Wed May 12 08:27:37 +0500 2021
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (MUSIC_repo_DA_II.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/conv_pkg.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/synth_reg.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/synth_reg_w_init.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/convert_type.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/xlclockdriver_rd.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/music_repo_da_ii_entity_declarations.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/music_repo_da_ii.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i0/music_repo_da_ii_c_addsub_v12_0_i0.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i1/music_repo_da_ii_c_addsub_v12_0_i1.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i0/music_repo_da_ii_mult_gen_v12_0_i0.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i1/music_repo_da_ii_mult_gen_v12_0_i1.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i2/music_repo_da_ii_mult_gen_v12_0_i2.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i2/music_repo_da_ii_c_addsub_v12_0_i2.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i3/music_repo_da_ii_c_addsub_v12_0_i3.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_counter_binary_v12_0_i0/music_repo_da_ii_c_counter_binary_v12_0_i0.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_counter_binary_v12_0_i1/music_repo_da_ii_c_counter_binary_v12_0_i1.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i3/music_repo_da_ii_mult_gen_v12_0_i3.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_blk_mem_gen_v8_3_i0/music_repo_da_ii_blk_mem_gen_v8_3_i0.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_blk_mem_gen_v8_3_i0_vivado.coe"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i4/music_repo_da_ii_c_addsub_v12_0_i4.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i4/music_repo_da_ii_mult_gen_v12_0_i4.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i5/music_repo_da_ii_mult_gen_v12_0_i5.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i5/music_repo_da_ii_c_addsub_v12_0_i5.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i6/music_repo_da_ii_c_addsub_v12_0_i6.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i7/music_repo_da_ii_c_addsub_v12_0_i7.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i8/music_repo_da_ii_c_addsub_v12_0_i8.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i6/music_repo_da_ii_mult_gen_v12_0_i6.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i7/music_repo_da_ii_mult_gen_v12_0_i7.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i9/music_repo_da_ii_c_addsub_v12_0_i9.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i10/music_repo_da_ii_c_addsub_v12_0_i10.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i8/music_repo_da_ii_mult_gen_v12_0_i8.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i9/music_repo_da_ii_mult_gen_v12_0_i9.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i11/music_repo_da_ii_c_addsub_v12_0_i11.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i12/music_repo_da_ii_c_addsub_v12_0_i12.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i10/music_repo_da_ii_mult_gen_v12_0_i10.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i11/music_repo_da_ii_mult_gen_v12_0_i11.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i12/music_repo_da_ii_mult_gen_v12_0_i12.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i13/music_repo_da_ii_mult_gen_v12_0_i13.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i13/music_repo_da_ii_c_addsub_v12_0_i13.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i14/music_repo_da_ii_mult_gen_v12_0_i14.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i0/music_repo_da_ii_div_gen_v5_1_i0.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i15/music_repo_da_ii_mult_gen_v12_0_i15.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i16/music_repo_da_ii_mult_gen_v12_0_i16.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i17/music_repo_da_ii_mult_gen_v12_0_i17.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i1/music_repo_da_ii_div_gen_v5_1_i1.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i2/music_repo_da_ii_div_gen_v5_1_i2.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i18/music_repo_da_ii_mult_gen_v12_0_i18.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i14/music_repo_da_ii_c_addsub_v12_0_i14.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i3/music_repo_da_ii_div_gen_v5_1_i3.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i19/music_repo_da_ii_mult_gen_v12_0_i19.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i20/music_repo_da_ii_mult_gen_v12_0_i20.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i21/music_repo_da_ii_mult_gen_v12_0_i21.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_cordic_v6_0_i0/music_repo_da_ii_cordic_v6_0_i0.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i15/music_repo_da_ii_c_addsub_v12_0_i15.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i16/music_repo_da_ii_c_addsub_v12_0_i16.xci"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/constrs_1/imports/sysgen/music_repo_da_ii_clock.xdc"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/constrs_1/imports/sysgen/music_repo_da_ii.xdc"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sim_1/imports/sysgen/music_repo_da_ii_tb.v"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_a.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_b.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_c.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_d.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_e.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_enable.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_f.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_da_ii_music_top_final_angle_da_ii.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_a.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_b.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_c.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_d.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_e.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_enable.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_f.dat"
#    "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/music_repo_final_music_top_gateway_out.dat"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "MUSIC_repo_DA_II.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist"]"

# Create project
create_project music_repo_da_ii ./music_repo_da_ii -part xc7z020clg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects music_repo_da_ii]
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "read write" $obj
set_property "ip_output_repo" "C:/Users/Home/Desktop/Patent/Response_to_reviews_25_Feb/MUSIC_opt/hdl_netlist/music_repo_da_ii.cache/ip" $obj
set_property "part" "xc7z020clg484-1" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj
set_property "xsim.array_display_limit" "64" $obj
set_property "xsim.trace_limit" "65536" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/conv_pkg.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/synth_reg.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/synth_reg_w_init.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/convert_type.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/xlclockdriver_rd.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/music_repo_da_ii_entity_declarations.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/music_repo_da_ii.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i0/music_repo_da_ii_c_addsub_v12_0_i0.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i1/music_repo_da_ii_c_addsub_v12_0_i1.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i0/music_repo_da_ii_mult_gen_v12_0_i0.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i1/music_repo_da_ii_mult_gen_v12_0_i1.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i2/music_repo_da_ii_mult_gen_v12_0_i2.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i2/music_repo_da_ii_c_addsub_v12_0_i2.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i3/music_repo_da_ii_c_addsub_v12_0_i3.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_counter_binary_v12_0_i0/music_repo_da_ii_c_counter_binary_v12_0_i0.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_counter_binary_v12_0_i1/music_repo_da_ii_c_counter_binary_v12_0_i1.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i3/music_repo_da_ii_mult_gen_v12_0_i3.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_blk_mem_gen_v8_3_i0/music_repo_da_ii_blk_mem_gen_v8_3_i0.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_blk_mem_gen_v8_3_i0_vivado.coe"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i4/music_repo_da_ii_c_addsub_v12_0_i4.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i4/music_repo_da_ii_mult_gen_v12_0_i4.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i5/music_repo_da_ii_mult_gen_v12_0_i5.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i5/music_repo_da_ii_c_addsub_v12_0_i5.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i6/music_repo_da_ii_c_addsub_v12_0_i6.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i7/music_repo_da_ii_c_addsub_v12_0_i7.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i8/music_repo_da_ii_c_addsub_v12_0_i8.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i6/music_repo_da_ii_mult_gen_v12_0_i6.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i7/music_repo_da_ii_mult_gen_v12_0_i7.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i9/music_repo_da_ii_c_addsub_v12_0_i9.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i10/music_repo_da_ii_c_addsub_v12_0_i10.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i8/music_repo_da_ii_mult_gen_v12_0_i8.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i9/music_repo_da_ii_mult_gen_v12_0_i9.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i11/music_repo_da_ii_c_addsub_v12_0_i11.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i12/music_repo_da_ii_c_addsub_v12_0_i12.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i10/music_repo_da_ii_mult_gen_v12_0_i10.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i11/music_repo_da_ii_mult_gen_v12_0_i11.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i12/music_repo_da_ii_mult_gen_v12_0_i12.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i13/music_repo_da_ii_mult_gen_v12_0_i13.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i13/music_repo_da_ii_c_addsub_v12_0_i13.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i14/music_repo_da_ii_mult_gen_v12_0_i14.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i0/music_repo_da_ii_div_gen_v5_1_i0.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i15/music_repo_da_ii_mult_gen_v12_0_i15.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i16/music_repo_da_ii_mult_gen_v12_0_i16.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i17/music_repo_da_ii_mult_gen_v12_0_i17.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i1/music_repo_da_ii_div_gen_v5_1_i1.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i2/music_repo_da_ii_div_gen_v5_1_i2.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i18/music_repo_da_ii_mult_gen_v12_0_i18.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i14/music_repo_da_ii_c_addsub_v12_0_i14.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_div_gen_v5_1_i3/music_repo_da_ii_div_gen_v5_1_i3.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i19/music_repo_da_ii_mult_gen_v12_0_i19.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i20/music_repo_da_ii_mult_gen_v12_0_i20.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_mult_gen_v12_0_i21/music_repo_da_ii_mult_gen_v12_0_i21.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_cordic_v6_0_i0/music_repo_da_ii_cordic_v6_0_i0.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i15/music_repo_da_ii_c_addsub_v12_0_i15.xci"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/ip/music_repo_da_ii_c_addsub_v12_0_i16/music_repo_da_ii_c_addsub_v12_0_i16.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sources_1/imports/sysgen/conv_pkg.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "music_repo_da_ii" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/constrs_1/imports/sysgen/music_repo_da_ii_clock.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/constrs_1/imports/sysgen/music_repo_da_ii_clock.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/constrs_1/imports/sysgen/music_repo_da_ii.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/constrs_1/imports/sysgen/music_repo_da_ii.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/../../MUSIC_opt/hdl_netlist/music_repo_da_ii.srcs/sim_1/imports/sysgen/music_repo_da_ii_tb.v"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_a.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_b.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_c.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_d.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_e.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_enable.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_f.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_final_angle_da_ii.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_a.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_b.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_c.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_d.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_e.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_enable.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_f.dat"]"\
 "[file normalize "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_gateway_out.dat"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_a.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_b.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_c.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_d.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_e.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_enable.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_f.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_da_ii_music_top_final_angle_da_ii.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_a.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_b.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_c.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_d.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_e.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_enable.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_f.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj

set file "$origin_dir/../../MUSIC_opt/music_repo_final_music_top_gateway_out.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Data Files" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "nl.sdf_anno" "0" $obj
set_property "runtime" "200210.00000000 ns" $obj
set_property "top" "music_repo_da_ii_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.more_options" " --timescale 1ns/10ps " $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.elaborate.xelab.more_options" " --timescale 1ns/10ps " $obj
set_property "xsim.simulate.runtime" "200210.00000000 ns" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7z020clg484-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7z020clg484-1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:music_repo_da_ii"
